version: '3.8'
services:
  db:
    build: .
    ports:
      - "5432:5432"

  backend:
    build: ./lab01
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_vinyl?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: eusevios
      SPRING_DATASOURCE_PASSWORD: 1234

  frontend:
    build: ./lab01/vinyl-client
    ports:
      - "4200:4200"
    depends_on:
      - backend